### PR TITLE
Testing

### LINKED ISSUE #22: Installation doesn't work because of packages that don't want to remove (cmdtest)
After a installation of synapse and remove of dendrite, (getting sick my messages and rooms BREAK at EVERY update of dendrite, losing all without any form of recovery). I tried to install the synapse admin, but installation doesn't seem to work.

I'm running yunohost last version on a PC on a  i3-3240T CPU.

Here the logs of the failed installation. Seems it's a problem with the script want to remove dependencies that synapase-ynh-deps put in at first place. Also, maybe the fact i have a custom yarn app that run, maybe ? I install synapse before the admin.

Synapse seem to been running fine.

https://paste.yunohost.org/raw/rixuvafoma

Thanks for the help, and the good work.

### LINKED ISSUE #24: development build -> production build -> yarn build
After fresh install I get following message:
https://paste.yunohost.org/eruxokaqex

### PR DESCRIPTION
**Pull request by ericgaspar**
Closes #24
Closes #22

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
