### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@tituspijean we may need to revert [ec2cc1d](https://github.com/YunoHost-Apps/synapse-admin_ynh/pull/36/commits/ec2cc1da12cf095ca0fd0688dba225f545f025a7)

**Comment by tituspijean** [comment]
Why? See [YunoHost-Apps/synapse-admin_ynh@`4c7acbd` (#35)](https://github.com/YunoHost-Apps/synapse-admin_ynh/pull/35/commits/4c7acbd70405ac43d8a74c02a6148f2cb8e32bb1), app build and service are not needed anymore.

**Comment by lapineige** [comment]
This app doesn't support SSO as far as I understand.
This means we have to expose it to visitors to access to it, right ?

**Comment by lapineige** [comment]
Nginx config is wrong : https://github.com/YunoHost-Apps/synapse-admin_ynh/issues/15#issuecomment-1519138408

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
!bookwormtestme

**Comment by lapineige** [comment]
@ericgaspar : does the CI fail because it's unreachable anyway ?

**Pull request closed without merging**
